### PR TITLE
Recursive addresses for

### PR DESCRIPTION
**Pull request by ioquatix**
@petergoldstein what do you think of this approach? Most existing functionality should be the same.

### CODE REVIEW

**Comment by ioquatix** [comment]
This is a potential fix for #31

**Comment by petergoldstein** [comment]
@ioquatix I can take a look at this, but probably not until tomorrow.

**Comment by ioquatix** [comment]
@petergoldstein Awesome, just if you have time.

The more I think about this PR, the more I am happy with it. The only think I'm not completely happy with is the Resolv::DNS::Name monkey patching.. initially it was useful but now not so much, it could probably be removed (`to_s` and `inspect`). It's a bit confusing when both absolute and relative names print out the same way.

**Comment by ioquatix** [comment]
Fixes #31

**Pull request merged**
